// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5jwgc-e9sAZfD_32H9lXwil8vRumQcEo',
    appId: '1:156649465222:web:b542437c1f348c413cb807',
    messagingSenderId: '156649465222',
    projectId: 'chat-app-8810a',
    authDomain: 'chat-app-8810a.firebaseapp.com',
    storageBucket: 'chat-app-8810a.firebasestorage.app',
    measurementId: 'G-0P5B6H9HGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB7P8GmwKIYRh6jIVlw9o9cKtaic3wyA8',
    appId: '1:156649465222:android:bfca7d65eaed82753cb807',
    messagingSenderId: '156649465222',
    projectId: 'chat-app-8810a',
    storageBucket: 'chat-app-8810a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyDKITeyudOV_d9dROnzcFjt9obM6ZwY',
    appId: '1:156649465222:ios:0c444f648a2a09bd3cb807',
    messagingSenderId: '156649465222',
    projectId: 'chat-app-8810a',
    storageBucket: 'chat-app-8810a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyDKITeyudOV_d9dROnzcFjt9obM6ZwY',
    appId: '1:156649465222:ios:0c444f648a2a09bd3cb807',
    messagingSenderId: '156649465222',
    projectId: 'chat-app-8810a',
    storageBucket: 'chat-app-8810a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5jwgc-e9sAZfD_32H9lXwil8vRumQcEo',
    appId: '1:156649465222:web:78a9fc1f2c88da383cb807',
    messagingSenderId: '156649465222',
    projectId: 'chat-app-8810a',
    authDomain: 'chat-app-8810a.firebaseapp.com',
    storageBucket: 'chat-app-8810a.firebasestorage.app',
    measurementId: 'G-17Q968EP51',
  );
}
